# Generated by Django 4.2.2 on 2023-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('something', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Something',
                'verbose_name_plural': 'Somethings',
                'ordering': ('-date_time', 'title'),
            },
        ),
    ]
