# Generated by Django 4.2.3 on 2023-07-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.TextField()),
                ('how_much_study', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
                'ordering': ('how_much_study',),
            },
        ),
        migrations.CreateModel(
            name='VuzName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='VUZ Name')),
                ('build_date', models.DateField(verbose_name='Build Date')),
                ('location', models.TextField(verbose_name='Location')),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'VUZ Name',
                'verbose_name_plural': 'VUZ Names',
                'ordering': ('capacity', '-build_date'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='FIO')),
                ('born_date', models.DateField(verbose_name='was_born')),
                ('where_born', models.TextField(verbose_name='Location')),
                ('course', models.IntegerField(verbose_name='which_course')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vuzes.speciality', verbose_name='Speciality')),
                ('vuz_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vuzes.vuzname', verbose_name='VUZ')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ('-born_date', 'course'),
            },
        ),
    ]
